'use strict';
const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
const e={imgIn:$('imageInput'),ws:$('imageWorkspace'),cv:$('imageCanvas'),ocr:$('ocrBtn'),ocrSt:$('ocrStatus'),src:$('sourceText'),out:$('maskedText'),mask:$('maskBtn'),restore:$('restoreTextBtn'),sum:$('detectSummary'),save:$('saveImageBtn'),copy:$('copyTextBtn'),toast:$('toast'),prep:$('prepareOfflineBtn'),help:$('installHelpBtn'),guide:$('installGuide'),net:$('networkChip'),off:$('offlineChip'),msg:$('offlineMessage'),prog:$('offlineProgress'),bar:$('offlineProgressBar'),progTxt:$('offlineProgressText'),imgMode:$('imageMode'),txtMode:$('textMode'),maskStep:$('maskStepLabel'),outStep:$('outputStepLabel'),undo:$('undoMaskBtn'),clear:$('clearMaskBtn')};
const ctx=e.cv.getContext('2d'); let base=null,dataUrl='',rects=[],draft=null,drag=false,snapshot='',ready=false,worker=null,reg=null,loadPromise=null;
const rules={email:{l:'[EMAIL]',r:/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi},phone:{l:'[PHONE]',r:/(?<!\d)(?:\+81[-\s]?)?(?:0\d{1,4}[-\s]?\d{1,4}[-\s]?\d{3,4})(?!\d)/g},postcode:{l:'[POSTCODE]',r:/(?<!\d)(?:〒\s*)?(?:\d{3}[-ー－]\d{4}|\d{7})(?!\d|[-ー－]\d)/g},url:{l:'[URL]',r:/\bhttps?:\/\/[^\s<>"']+/gi},number:{l:'[NUMBER]',r:/(?<!\d)(?:\d[\s-]?){8,}\d(?!\d)/g}};
function toast(t,err=false){e.toast.textContent=t;e.toast.style.color=err?'#8f3434':'#335f4a';clearTimeout(toast.t);toast.t=setTimeout(()=>e.toast.textContent='',3000)}
function network(){const on=navigator.onLine;e.net.textContent=on?'ONLINE':'OFFLINE';e.net.classList.toggle('is-ready',on);e.net.classList.toggle('is-offline',!on)} addEventListener('online',network);addEventListener('offline',network);network();
function setReady(v){ready=!!v;e.off.textContent=ready?'OCR READY':'OCR 未準備';e.off.classList.toggle('is-ready',ready);e.prep.textContent=ready?'✓ オフライン準備済み':'オフライン準備をする';e.prep.disabled=ready;e.ocr.disabled=!ready||!base;e.msg.textContent=ready?'OCRパックはこの端末に保存済みです。機内モードでも利用できます。':(navigator.onLine?'初回だけOCRパックをこのiPhoneへ保存します。':'OCRパックが未準備です。オンライン時に一度だけ準備してください。');if(ready)loadTesseract().catch(()=>{})}
function swMsg(ev){const d=ev.data||{};if(d.type==='OCR_STATUS')setReady(d.ready);if(d.type==='OCR_CACHE_PROGRESS'){e.prog.classList.remove('is-hidden');const p=Math.round(d.done/d.total*100);e.bar.style.width=p+'%';e.progTxt.textContent=`OCRパックを保存中… ${d.done}/${d.total}`;}if(d.type==='OCR_CACHE_READY'){e.bar.style.width='100%';e.progTxt.textContent='✓ オフライン準備が完了しました。';setReady(true);toast('✓ これで機内モードでもOCRできます。')}if(d.type==='OCR_CACHE_ERROR'){e.prep.disabled=false;e.progTxt.textContent='保存に失敗しました。通信を確認して再試行してください。';toast('OCRパックの保存に失敗しました。',true)}}
async function initSW(){if(!('serviceWorker'in navigator)){e.off.textContent='非対応';e.prep.disabled=true;return}try{reg=await navigator.serviceWorker.register('./sw.js',{scope:'./'});await navigator.serviceWorker.ready;navigator.serviceWorker.addEventListener('message',swMsg);(navigator.serviceWorker.controller||reg.active)?.postMessage({type:'GET_OCR_STATUS'})}catch(x){console.error(x);e.off.textContent='準備不可';e.msg.textContent='HTTPSで開いているか確認してください。'}}
e.prep.onclick=()=>{if(!navigator.onLine)return toast('初回準備だけはインターネット接続が必要です。',true);const w=navigator.serviceWorker.controller||reg?.active;if(!w)return toast('ページを一度再読み込みしてください。',true);e.prep.disabled=true;e.prog.classList.remove('is-hidden');e.bar.style.width='2%';e.progTxt.textContent='OCRパックの保存を開始します…';w.postMessage({type:'CACHE_OCR_ASSETS'})};e.help.onclick=()=>e.guide.classList.toggle('is-hidden');
function loadTesseract(){if(window.Tesseract)return Promise.resolve(window.Tesseract);if(loadPromise)return loadPromise;loadPromise=new Promise((ok,ng)=>{const s=document.createElement('script');s.src='./offline/tesseract.min.js';s.onload=()=>window.Tesseract?ok(window.Tesseract):ng();s.onerror=ng;document.head.appendChild(s)});return loadPromise}
async function getWorker(log){if(worker)return worker;await loadTesseract();const abs=p=>new URL(p,location.href).href.replace(/\/$/,'');worker=await Tesseract.createWorker(['jpn','eng'],1,{workerPath:abs('./offline/worker.min.js'),corePath:abs('./offline/core'),langPath:abs('./offline/lang'),logger:log});return worker}
function mode(m){$$('.mode-btn').forEach(b=>b.classList.toggle('is-active',b.dataset.mode===m));e.imgMode.classList.toggle('is-hidden',m!=='image');e.txtMode.classList.toggle('is-hidden',m!=='text');e.maskStep.textContent=m==='image'?'STEP 3':'STEP 2';e.outStep.textContent=m==='image'?'STEP 4':'STEP 3';e.save.disabled=m==='text'||!base;if(m==='text')setTimeout(()=>e.src.focus(),0)} $$('.mode-btn').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
function fit(img){const s=Math.min(1,2200/Math.max(img.naturalWidth,img.naturalHeight));e.cv.width=Math.max(1,Math.round(img.naturalWidth*s));e.cv.height=Math.max(1,Math.round(img.naturalHeight*s))}
function draw(withDraft=true){if(!base)return;ctx.clearRect(0,0,e.cv.width,e.cv.height);ctx.drawImage(base,0,0,e.cv.width,e.cv.height);ctx.fillStyle='#000';rects.forEach(r=>ctx.fillRect(r.x,r.y,r.w,r.h));if(withDraft&&draft){ctx.save();ctx.fillStyle='rgba(0,0,0,.68)';ctx.fillRect(draft.x,draft.y,draft.w,draft.h);ctx.restore()}}
function loadImage(f){if(!f)return;if(!/^image\/(png|jpeg|webp)$/.test(f.type))return toast('PNG / JPG / WebP を選択してください。',true);const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{base=img;dataUrl=String(r.result);rects=[];fit(img);draw();e.ws.classList.remove('is-hidden');e.save.disabled=false;e.ocr.disabled=!ready;e.ocrSt.textContent=ready?'OCRを実行できます。':'先にオフライン準備を完了してください。'};img.src=String(r.result)};r.readAsDataURL(f)} e.imgIn.onchange=x=>loadImage(x.target.files?.[0]);
function pt(ev){const r=e.cv.getBoundingClientRect();return{x:(ev.clientX-r.left)*e.cv.width/r.width,y:(ev.clientY-r.top)*e.cv.height/r.height}}
e.cv.onpointerdown=ev=>{if(!base)return;drag=true;e.cv.setPointerCapture(ev.pointerId);const p=pt(ev);draft={x:p.x,y:p.y,w:0,h:0,sx:p.x,sy:p.y};draw()};e.cv.onpointermove=ev=>{if(!drag||!draft)return;const p=pt(ev);draft.x=Math.min(draft.sx,p.x);draft.y=Math.min(draft.sy,p.y);draft.w=Math.abs(p.x-draft.sx);draft.h=Math.abs(p.y-draft.sy);draw()};function end(ev){if(!drag||!draft)return;drag=false;try{e.cv.releasePointerCapture(ev.pointerId)}catch{}if(draft.w>4&&draft.h>4)rects.push({x:draft.x,y:draft.y,w:draft.w,h:draft.h});draft=null;draw()} e.cv.onpointerup=end;e.cv.onpointercancel=end;e.undo.onclick=()=>{rects.pop();draw()};e.clear.onclick=()=>{rects=[];draw()};
function maskText(t){const keys=$$('input[name="detect"]:checked').map(i=>i.value),counts={};for(const k of ['url','email','postcode','phone','number'])if(keys.includes(k)){let n=0;t=t.replace(rules[k].r,()=>{n++;return rules[k].l});counts[k]=n}return{t,counts}}
e.mask.onclick=()=>{if(!e.src.value.trim())return toast('まず文章を入力してください。',true);snapshot=e.src.value;const x=maskText(e.src.value);e.out.value=x.t;const nm={email:'メール',phone:'電話番号',postcode:'郵便番号',url:'URL',number:'長い数字列'},parts=Object.entries(x.counts).filter(([,n])=>n).map(([k,n])=>`${nm[k]} ${n}件`),total=Object.values(x.counts).reduce((a,b)=>a+b,0);e.sum.innerHTML=total?`<strong>${total}件をマスクしました。</strong><span>${parts.join(' / ')}。人名・住所・会社名は必要に応じて手動編集してください。</span>`:'<strong>対象は見つかりませんでした。</strong><span>人名・住所・会社名などは手動で編集してください。</span>'};e.restore.onclick=()=>{if(!snapshot)return toast('戻せる元テキストがありません。',true);e.src.value=snapshot;e.out.value=''};
e.copy.onclick=async()=>{const t=(e.out.value||e.src.value).trim();if(!t)return toast('コピーする文章がありません。',true);try{await navigator.clipboard.writeText(t);toast('✓ AI用テキストをコピーしました。')}catch{const x=e.out.value?e.out:e.src;x.focus();x.select();toast(document.execCommand('copy')?'✓ AI用テキストをコピーしました。':'コピーできませんでした。',true)}};
e.save.onclick=()=>{if(!base)return;draw(false);e.cv.toBlob(async b=>{if(!b)return;const f=new File([b],`mask-${new Date().toISOString().slice(0,10)}.png`,{type:'image/png'});try{if(navigator.canShare?.({files:[f]})&&navigator.share){await navigator.share({files:[f],title:'MASK 共有用画像'});return}}catch(x){if(x.name==='AbortError')return}const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)},'image/png')};
e.ocr.onclick=async()=>{if(!base||!dataUrl)return;if(!ready)return toast('先にオフライン準備を完了してください。',true);e.ocr.disabled=true;try{const w=await getWorker(m=>{if(m?.status)e.ocrSt.textContent=`OCR処理中… ${typeof m.progress==='number'?Math.round(m.progress*100)+'%':''}`});const r=await w.recognize(dataUrl),t=r?.data?.text?.trim()||'';e.src.value=t;snapshot=t;e.ocrSt.textContent=t?'✓ 文字を読み取りました。':'文字を検出できませんでした。'}catch(x){console.error(x);worker=null;e.ocrSt.textContent='OCRに失敗しました。オフライン準備をやり直してください。'}finally{e.ocr.disabled=!ready}};
mode('image');setReady(false);initSW();
